name: 1.0$(Rev:.r)

resources:
  repositories:
    - repository: templates
      type: github
      name: goformz/devops-templates
      endpoint: github

trigger:
  - master
  - develop
  - release-*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  lfs: true
  submodules: true
- template: build-netcore.yml@templates
  parameters:
    GithubToken: '$(GithubToken)'
    runTests: false
    dotNetVersion: '6.0.x'
    projects: 'KeyVault.Acmebot/KeyVault.Acmebot.csproj'
